### ISSUE TITLE
Tidyverse Workshop 

### ISSUE THREAD

**Issue by Emsty428** [Athanasiamo/tidyquintro#1]
Dear Athanasia,
 
I loaded the R packages for the tidyverse workshop. It all went fine except for this section:
 
When these are successful, you should be able to install the course package. Download the newest tar-version from the source directory, and install with

install.packages("/path/to/tidyquintro_0.1.01.tar.gz", repos = NULL)
 
 
When I entered this I got the message: > install.packages("/path/to/tidyquintro_0.1.01.tar.gz", repos = NULL)
Installing package into ‘/Users/stobbe/Library/R/4.0/library’
(as ‘lib’ is unspecified)
Warnung: ungültiges Paket ‘/path/to/tidyquintro_0.1.01.tar.gz’
Fehler: Fehler: keine Pakete angegeben
Warning in install.packages :
  installation of package ‘/path/to/tidyquintro_0.1.01.tar.gz’ had non-zero exit status
 
I am able to load the library(tidyquintro) so I am not sure what is now working and what is not working, all the other installations went fine.
 
Can you help me with this tat would be really great!
 
Best wishes,
Emil Stobbe

**Comment by drmowinckels** [comment]
Hi Emil

Thanks for getting in touch.

I suspect that the first installation worked just fine using the code:

```r
install.packages("remotes")
remotes::install_github("Athanasiamo/tidyquintro")
```

Then everything is fine, and that would be why loading it is also working.

The second install part was only intended to be needed _if_ the above did not work.

All the best,
— Mo

**Comment by Emsty428** [comment]
Hi Athanasia,

thank you fort he quick reply! Good that it worked, however if I call the library it tells me that there are still some conflicts is that a problem?

Lade nötiges Paket: tidyverse
── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──
✓ ggplot2 3.3.2     ✓ purrr   0.3.4
✓ tibble  3.0.1     ✓ dplyr   0.8.5
✓ tidyr   1.1.2     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.5.0
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()
Lade nötiges Paket: broom
Lade nötiges Paket: palmerpenguins


Thanks again for you advice, looking forward to the workshop tomorrow!
Best,
Emil

**Comment by drmowinckels** [comment]
Great that everything is fine

That is as expected :)

I will talk about the conflicts slightly tomorrow. That warning will _always_ app read when you load the tidyverse.

—Mo

**Comment by Emsty428** [comment]
Dear Athanasia,

I have an urgent request, would it possible for me to be allocated in the Wednesday group for the tidyverse workshop?  This way I can attend a meeting with out lab today and join tomorrow for the workshop. Let me know if that is possible Thank you!
Best,
Emil Stobbe

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by drmowinckels** [comment]
I think that is ok for me, but you will also need to contact the libraries organising it.
Let them know I thought it was ok.

-Mo


Athanasia Monika Mowinckel
Staff scientist

Phone: +47 22845022
e-mail: a.m.mowinckel@psykologi.uio.no<mailto:a.m.mowinckel@psykologi.uio.no>

Center for Lifespan Changes in Brain and Cognition (LCBC)
Department of Psychology
University of Oslo
POB 1094 Blindern
0317 Oslo
Norway

[LCBC] <https://www.oslobrains.no/>

[Lifebrain] <https://www.lifebrain.uio.no//>


On 15 September 2020 at 08:18:10, Emsty428 (notifications@github.com<mailto:notifications@github.com>) wrote:

Dear Athanasia,

I have an urgent request, would it possible for me to be allocated in the Wednesday group for the tidyverse workshop? This way I can attend a meeting with out lab today and join tomorrow for the workshop. Let me know if that is possible Thank you!
Best,
Emil Stobbe

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
